// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: weatherForecast.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherForecastService_GetMarineWaveHeight_FullMethodName = "/example.WeatherForecastService/GetMarineWaveHeight"
)

// WeatherForecastServiceClient is the client API for WeatherForecastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherForecastServiceClient interface {
	// Define the method
	GetMarineWaveHeight(ctx context.Context, in *MarineWaveHeightForecastReq, opts ...grpc.CallOption) (*MarineForecast, error)
}

type weatherForecastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherForecastServiceClient(cc grpc.ClientConnInterface) WeatherForecastServiceClient {
	return &weatherForecastServiceClient{cc}
}

func (c *weatherForecastServiceClient) GetMarineWaveHeight(ctx context.Context, in *MarineWaveHeightForecastReq, opts ...grpc.CallOption) (*MarineForecast, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarineForecast)
	err := c.cc.Invoke(ctx, WeatherForecastService_GetMarineWaveHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherForecastServiceServer is the server API for WeatherForecastService service.
// All implementations must embed UnimplementedWeatherForecastServiceServer
// for forward compatibility.
type WeatherForecastServiceServer interface {
	// Define the method
	GetMarineWaveHeight(context.Context, *MarineWaveHeightForecastReq) (*MarineForecast, error)
	mustEmbedUnimplementedWeatherForecastServiceServer()
}

// UnimplementedWeatherForecastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherForecastServiceServer struct{}

func (UnimplementedWeatherForecastServiceServer) GetMarineWaveHeight(context.Context, *MarineWaveHeightForecastReq) (*MarineForecast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarineWaveHeight not implemented")
}
func (UnimplementedWeatherForecastServiceServer) mustEmbedUnimplementedWeatherForecastServiceServer() {
}
func (UnimplementedWeatherForecastServiceServer) testEmbeddedByValue() {}

// UnsafeWeatherForecastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherForecastServiceServer will
// result in compilation errors.
type UnsafeWeatherForecastServiceServer interface {
	mustEmbedUnimplementedWeatherForecastServiceServer()
}

func RegisterWeatherForecastServiceServer(s grpc.ServiceRegistrar, srv WeatherForecastServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherForecastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherForecastService_ServiceDesc, srv)
}

func _WeatherForecastService_GetMarineWaveHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarineWaveHeightForecastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherForecastServiceServer).GetMarineWaveHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherForecastService_GetMarineWaveHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherForecastServiceServer).GetMarineWaveHeight(ctx, req.(*MarineWaveHeightForecastReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherForecastService_ServiceDesc is the grpc.ServiceDesc for WeatherForecastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherForecastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.WeatherForecastService",
	HandlerType: (*WeatherForecastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarineWaveHeight",
			Handler:    _WeatherForecastService_GetMarineWaveHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weatherForecast.proto",
}
